"""empty message

Revision ID: 747888c34864
Revises: 9a8506a42c03
Create Date: 2023-10-25 20:23:04.595457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '747888c34864'
down_revision = '9a8506a42c03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    # ### end Alembic commands ###
