"""Add speaker column

Revision ID: 9a8506a42c03
Revises: 
Create Date: 2023-10-25 18:41:46.389339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a8506a42c03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('speaker', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('type')
        batch_op.drop_column('speaker')

    # ### end Alembic commands ###
